### ISSUE TITLE
About memory optimization and model distillation

### ISSUE THREAD

**Issue by KoDelioDa** [jianzongwu/DiffSensei#2]
I am a 3090 graphics card with 24GB of memory, but I still cannot use inference, and I have downloaded nearly 130GB of models in total, whether it can be optimized

**Comment by iddl** [comment]
Not directly addressing your comment, but, for anyone reading, this runs on A100 with 40gb on memory. I didn't see anything about hardware requirements in the readme.

`nvidia-smi` output below
```
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     22228      C   python                                      34930MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by jianzongwu** [comment]
Thank you for your feedback, and we sincerely apologize for the inconvenience caused by the large model requirements.

To address this issue, we are working on releasing an optimized version that will use significantly less memory. This version will feature only the image generator without the MLLM component, which is the primary contributor to high memory usage. While this change will reduce some text compatibility features, it will not significantly affect the overall quality of the generated images.

We hope this will provide a smoother experience for users like you with high-performance GPUs but memory constraints. Thank you for your patience, and we appreciate your support!

**Comment by onemore118** [comment]
> Thank you for your feedback, and we sincerely apologize for the inconvenience caused by the large model requirements.
> 
> To address this issue, we are working on releasing an optimized version that will use significantly less memory. This version will feature only the image generator without the MLLM component, which is the primary contributor to high memory usage. While this change will reduce some text compatibility features, it will not significantly affect the overall quality of the generated images.
> 
> We hope this will provide a smoother experience for users like you with high-performance GPUs but memory constraints. Thank you for your patience, and we appreciate your support!

When performing model inference without the MLLM module, will the capabilities related to character poses and expressions be lost?

**Comment by jianzongwu** [comment]
> [onemore118](/onemore118)

Will loss a bit. You can see the ablation study in our [paper](https://arxiv.org/abs/2412.07589) for more details
