### ISSUE TITLE
I believe this is a groundbreaking innovation

### ISSUE THREAD

**Issue by tsjslgy** [jianzongwu/DiffSensei#3]
As a seasoned manga enthusiast who can also create my own comics, I’ve noticed a significant boost in efficiency since I started using AI. My dream is to one day control AI with just language to produce artwork, and I’m eagerly anticipating the arrival of that day as AI continues to evolve.
Back to the topic, I haven’t had the chance to try it yet, as it seems to have high hardware requirements. I completely understand that new technologies require time for optimization, but I do have some concerns. If it cannot be integrated with Stable Diffusion’s LoRA, how can we create more complex scenes or characters? I assume progress is being made on colorization as well—please keep up the great work. Finally, I hope this technology can eventually run on standard consumer devices, which would be ideal.

**Comment by 99bits** [comment]
Super incredible work @jianzongwu and team.  
I'm also curious how to expand the model's styles and composition.  
Also is it possible to generate the model without the text bubbles because I would like to style the text bubbles differently.   What would be ideal is that the generated images have free areas for text bubbles but not actually have the text bubbles.  This way I can use that free area for placement of my custom text bubbles.  

Cheers.

**Comment by jianzongwu** [comment]
Hi, please check our [paper](https://arxiv.org/abs/2412.07589) for more details of training.

For controlling on styles and dialog bubble styles, I think you can collect such dataset and add style embedding modules to control them.

**Comment by 99bits** [comment]
Thanks @jianzongwu, will give it a shot.
